image:
  repository: flaskecommerceacr.azurecr.io/flask-ecommerce
  tag: latest

replicaCount: 2

service:
  type: LoadBalancer
  port: 5000
  targetPort: 5000  # Ensure the service points to the correct target port of the container

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Add the image pull secrets here to ensure Kubernetes can access the ACR
imagePullSecrets:
  - name: acr-secret
