apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ecommerce
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-ecommerce
  template:
    metadata:
      labels:
        app: flask-ecommerce
    spec:
      containers:
      - name: flask-ecommerce
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
