name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Enable write permission for the id-token
      contents: read   # Allow read permissions for repository contents

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: |
        docker build -t flask-ecommerce .

    - name: Push Docker image to ACR
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
        docker tag flask-ecommerce ${{ secrets.ACR_LOGIN_SERVER }}/flask-ecommerce:latest
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/flask-ecommerce:latest

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        debug: true  # Enable debug mode for more verbose output

    - name: Set up Kubernetes context
      run: |
        az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Verify Kubernetes connection
      run: |
        kubectl get nodes

    - name: Deploy to AKS with Helm
      run: |
        helm upgrade --install flask-ecommerce helm_chart/
