name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: |
        docker build -t flask-ecommerce .

    - name: Push Docker image to Azure Container Registry
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
        docker tag flask-ecommerce ${{ secrets.ACR_LOGIN_SERVER }}/flask-ecommerce:latest
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/flask-ecommerce:latest

    - name: Validate Kubernetes Cluster Access
      run: |
        kubectl cluster-info


    - name: Install Helm
       run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy to Azure Kubernetes Service
       env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
       run: |
         helm upgrade --install flask-ecommerce helm_chart \
          --set image.repository=${{ secrets.ACR_LOGIN_SERVER }}/flask-ecommerce \
          --set image.tag=latest
