name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install the dependencies from the requirements file
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Build Docker image for the Flask app
    - name: Build Docker image
      run: |
        docker build -t flask-ecommerce .

    # Log in to Azure Container Registry (ACR)
    - name: Log in to ACR
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    # Tag and push Docker image to ACR
    - name: Push Docker image to ACR
      run: |
        docker tag flask-ecommerce ${{ secrets.ACR_LOGIN_SERVER }}/flask-ecommerce:latest
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/flask-ecommerce:latest

    # Set up Helm to deploy the app to AKS
    - name: Set up Helm
      uses: azure/setup-helm@v1

    # Log in to Azure using Azure CLI (ensure AKS access)
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Set the Kubernetes context for AKS
    - name: Set up kubectl context
      run: |
        az aks get-credentials --resource-group flask-ecommerce-rg --name flask-ecommerce-aks

    # Deploy the app to AKS using Helm
    - name: Deploy to AKS
      run: |
        helm upgrade --install flask-ecommerce helm_chart/ --namespace default --set image.repository=${{ secrets.ACR_LOGIN_SERVER }}/flask-ecommerce,image.tag=latest
